project:
  type: website
  render: 
    - "index.qmd"
    - "syllabus.qmd"
    - "setup.qmd"
    - "lectures/"
    - "!labs/"
    - "!homework/"
    - "!project/"
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto



