project:
  type: website

website:
  title: "36-315"
  navbar:
    background: "#f8f8f8"
    right:
      - href: index.qmd
        text: "**Home**"
      - href: syllabus.qmd
        text: "**Syllabus**"
      - href: lectures.qmd
        text: "**Lectures**"

format:
  html:
    theme: yeti
    fontsize: 0.95em
    css: styles.css
    
execute:
  freeze: auto



