---
title: "36-315: Statistical Graphics and Visualization"
subtitle: "Carnegie Mellon University, Summer 2026"
listing:
  - id: buttons
    template: buttons.ejs
    contents: buttons.yml
format:
  html:
    page-layout: article
---

##### **Instructor:** Quang Nguyen
##### **Lectures:** MWF 12:30--1:50pm, SH 234
##### **Labs:** TR 12:30--1:50pm, BH 140B
##### **Office hours:** W 2--3pm
##### {-}

::: {#buttons}
:::

## Lectures

* Lecture 1: The grammar of graphics and ggplot2 [slides](lectures/lecture01.qmd)
* Lecture 2: Visualizing 1D categorical data [slides](lectures/lecture02.qmd)

<!-- * Lecture 3: Statistical inference for 1D categorical data  [slides](lectures/lecture03.qmd) -->
<!-- * Lecture 4: Visualizations and inference for 2D categorical data  [slides](lectures/lecture04.qmd) -->

## Labs

* Lab 1: [assignment](labs/lab1.qmd)

<!-- * Lab 2: [assignment](labs/lab2.qmd) -->
<!-- * Lab 3: [assignment](labs/lab3.qmd) -->

## Homework

* Homework 1: [assignment](homework/homework1.qmd)

## Graphic Critiques

* TBA

<!-- * Critique 1: [template](critiques/critique1.qmd) -->
<!-- * Critique 2: [template](critiques/critique2.qmd) -->

## Final Project

* TBA

<!-- * Project: [guide](project/project-guide.qmd) -->
<!-- * Report: [guide](project/report-guide.qmd), [template](project/report-template.qmd) -->
<!-- * Presentation: [guide](project/presentation-guide.qmd) -->

## Calendar

*(subject to change; all times ET)*

<details open>
<summary><strong>Week 1</strong></summary>
| Date                | Session      | Due                  |
|---------------------|--------------|----------------------|
| May 11 (Monday)     | Lecture 1    |                      |
| May 12 (Tuesday)    | Lab 1        | Lab 1 @ 11:59pm      |
| May 13 (Wednesday)  | Lecture 2    |                      |
| May 14 (Thursday)   | Lab 2        | Lab 2 @ 11:59pm      |
| May 15 (Friday)     | Lecture 3    | Homework 1 @ 11:59pm |
</details>

<details>
<summary><strong>Week 2</strong></summary>
| Date                | Session      | Due                  |
|---------------------|--------------|----------------------|
| May 18 (Monday)     | Lecture 4    |                      |
| May 19 (Tuesday)    | Lab 3        | Lab 3 @ 11:59pm      |
| May 20 (Wednesday)  | Lecture 5    |                      |
| May 21 (Thursday)   | Lab 4        | Lab 4 @ 11:59pm      |
| May 22 (Friday)     | Lecture 6    | Homework 2 @ 11:59pm |
</details>

<details>
<summary><strong>Week 3</strong></summary>
| Date                | Session      | Due                  |
|---------------------|--------------|----------------------|
| May 25 (Monday)     | Memorial Day |                      |
| May 26 (Tuesday)    | Lab 5        | Lab 5 @ 11:59pm      |
| May 27 (Wednesday)  | Lecture 7    | Critique 1 @ 11:59pm |
| May 28 (Thursday)   | Lab 6        | Lab 6 @ 11:59pm      |
| May 29 (Friday)     | Lecture 8    | Homework 3 @ 11:59pm |
</details>

<details>
<summary><strong>Week 4</strong></summary>
| Date                | Session      | Due                  |
|---------------------|--------------|----------------------|
| June 1 (Monday)     | Lecture 9    |                      |
| June 2 (Tuesday)    | NO LAB       | Take-home @ 11:59pm  |
| June 3 (Wednesday)  | Lecture 10   |                      |
| June 4 (Thursday)   | Lab 7        | Lab 7 @ 11:59pm      |
| June 5 (Friday)     | Lecture 11   | Homework 4 @ 11:59pm |
</details>

<details>
<summary><strong>Week 5</strong></summary>
| Date                | Session      | Due                  |
|---------------------|--------------|----------------------|
| June 8 (Monday)     | Lecture 12   |                      |
| June 9 (Tuesday)    | Lab 8        | Lab 8 @ 11:59pm      |
| June 10 (Wednesday) | Lecture 13   | Critique 2 @ 11:59pm |
| June 11 (Thursday)  | Lab 9        | Lab 9 @ 11:59pm      |
| June 12 (Friday)    | Lecture 14   | Homework 5 @ 11:59pm |
</details>

<details>
<summary><strong>Week 6</strong></summary>
| Date                | Session      | Due                  |
|---------------------|--------------|----------------------|
| June 15 (Monday)    | Lecture 15   |                      |
| June 16 (Tuesday)   | TBD          |                      |
| June 17 (Wednesday) | TBD          | Project @ 11:59pm    |
</details>