---
title: "Syllabus"
subtitle: "36-315: Statistical Graphics and Visualization, Summer 2026"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-block-background: true
---

## Basic Information

::: {.grid}

::: {.g-col-3}
**Instructor**
:::

::: {.g-col-9}
Quang Nguyen ([quang@stat.cmu.edu](mailto:quang@stat.cmu.edu))

Office Hours: W 2--3pm
:::

:::

::: {.grid}

::: {.g-col-3}
**Website**
:::

::: {.g-col-9}
[36-315-summer26.netlify.app](https://36-315-summer26.netlify.app/)<br>
*(Note: Assignments should be submitted through [Gradescope](https://www.gradescope.com))*
:::

:::

::: {.grid}

::: {.g-col-3}
**Textbooks**
:::

::: {.g-col-9}
None required.
Lecture slides will be posted.
Other references will be provided throughout the course.
:::

:::

::: {.grid}

::: {.g-col-3}
**Software**
:::

::: {.g-col-9}
**R** (programming language), **RStudio** (IDE), and  **Quarto** (reproducible documents)

:::

:::

::: {.grid}

::: {.g-col-3}
**Lectures**
:::

::: {.g-col-9}
MWF 12:30--1:50pm, SH 234
:::

:::

::: {.grid}

::: {.g-col-3}
**Labs**
:::

::: {.g-col-9}
TR 12:30--1:50pm, BH 140B
:::

:::

::: {.grid}

::: {.g-col-3}
**Weekly Assignments**
:::

::: {.g-col-9}
Labs are due on Tuesdays/Thursdays by 11:59pm.<br>
Homeworks are due on Fridays by 11:59pm.
:::

:::

::: {.grid}

::: {.g-col-3}
**Graphic Critiques**
:::

::: {.g-col-9}
Two graphic critiques, due Wednesday, May 27 and Wednesday, June 10.
:::

:::

::: {.grid}

::: {.g-col-3}
**Take-Home Exam**
:::

::: {.g-col-9}
One take-home exam on Tuesday, June 2.
:::

:::

::: {.grid}

::: {.g-col-3}
**Final Project**
:::

::: {.g-col-9}
Includes a report and a video presentation, both due Wednesday, June 18.
:::

:::

::: {.grid}

::: {.g-col-3}
**Grading**
:::

::: {.g-col-9}

25% Homework

15% Lab

20% Take-Home Exam

10% Graphic Critique

30% Final Project

Final grades are computed based on the weighting scheme above.

**No assignments are dropped when calculating grades.**

Final letter grades will be based on the standard 10-point scale
(A: 90--100, B: 80--89, C: 70--79, D: 60--69, R: 0--59).
Grades will be rounded, such that an 89.50% would be an A, but an 89.49% would not.

Final semester grades may be curved, but the curve will never lead to a worse grade than the 10-point scale.
For example, a grade of 85% would earn you at least a B, and a curve could only improve it.

:::

:::

## Overview

::: {.grid}

::: {.g-col-3}
**TL;DR**
:::

::: {.g-col-9}
This is a **6-week** summer course on statistical graphics and visualization.
**This course moves extremely fast.**
:::

:::

::: {.grid}

::: {.g-col-3}
**Description**
:::

::: {.g-col-9}
Graphical displays of quantitative information take on many forms, and they help us understand data and statistical methods by (hopefully) clearly communicating arguments, results, and ideas.
This course introduces students to the most common forms of graphical displays and their uses and misuses.
Students will learn how to create these displays and understand them from a statistical perspective.
Furthermore, the course will consider complex data structures that are becoming increasingly common in data visualizations (temporal, spatial, and textual); we will discuss common ways to process these data that make them easy to visualize.
All assignments will be in **R**; although this is not a programming class, using software like **R** is essential to create modern-day graphics. Throughout, communication skills (visual, written, and oral) will play an important role.
Indeed, if it's true that "a picture speaks a thousand words," then ideally the one thousand words you are communicating with your graphics are statistically correct, clear, and compelling.
:::

:::

::: {.grid}

::: {.g-col-3}
**Learning Objectives**
:::

::: {.g-col-9}
**1. Understand the fundamentals of data and reproducible workflows**

* Distinguish between data types and pinpoint which graphics and analyses are appropriate for a particular data type.

* Write readable, reproducible code to explore data visually.

* Master the use of **R**, **RStudio**, **Quarto**, and other tools to promote reproducible research and allow others to build from your work.

**2. Create high-quality statistical graphics**

* Master the use of **ggplot2** to create statistical graphics that are easily readable and understandable for technical and non-technical audiences.

* Incorporate statistical information (e.g., the results of statistical tests or uncertainty quantification) into elegant data visualizations.

**3. Assess and critique statistical graphics**

* Review statistical graphics objectively and professionally.

* Describe the pros and cons of a given graphical choice.

* Give useful suggestions for improvement.

**4. Write and communicate about statistical graphics and data visualizations**

* Describe graphics concisely and accurately to technical and non-technical audiences.

* Incorporate appropriate statistical language in descriptions of graphics.

:::

:::

## Components

::: {.grid}

::: {.g-col-3}
**Lectures**
:::

::: {.g-col-9}
Almost all course content will be covered during lecture.
Lectures will prepare you for subsequent assignments.
If you miss a lecture, you are responsible for the material covered.

Please participate and ask questions during lecture.
And please make a habit of showing up on time.
Consistent tardiness is not acceptable and may lead to grade deductions.

:::

:::

::: {.grid}

::: {.g-col-3}
**Labs**
:::

::: {.g-col-9}

Bi-weekly labs give students opportunities to engage with the course materials.
Each lab will be turned in as a lab assignment.
Labs are designed to be completed during the session, but they are not due until 11:59pm on the day of the lab, so students have extra time if needed.
**Labs must be completed in a Quarto document and submitted on Gradescope as a pdf file.**

Live lab attendance is **mandatory.**
As with lectures, please arrive to labs on time.
If you submit a lab assignment but did not show up to lab, there is an automatic **20 point** deduction.
However, if you need to miss a lab for a valid reason, contact the instructor at least **24 hours** before the lab to discuss doing the lab on your own and getting full credit.
If there is an unexpected emergency, notify the instructor immediately.
It is up to the instructor to determine if an accommodation is possible.
:::

:::

::: {.grid}

::: {.g-col-3}
**Homeworks**
:::

::: {.g-col-9}
Homework assignments are due on Fridays by 11:59pm, and will be posted on Mondays of the same week.
**Homeworks must be completed in a Quarto document and submitted on Gradescope as a pdf file.**
Be sure that your code, graphs, and answers are properly displayed on your homework before submitting.
:::

:::

::: {.grid}

::: {.g-col-3}
**Graphic Critiques**
:::

::: {.g-col-9}
Data visualizations can be found everywhere.
In the course, you will submit two critiques of data visualizations you find.
These must be from a recent source that was posted online for the first time within the **past year** (i.e., not from some 2011 blog post) and can **not** be an example from lecture, labs, or homework.

A graphic critique assignment template (using Quarto) will be provided.
You will get practice doing this on the first homework.
Then, you will submit two graphic critiques during the semester.
The due dates for each critique are **Wednesday, May 27, 11:59pm** and **Wednesday, June 10, 11:59pm**.
These are meant to be light and entertaining exercises.
:::

:::

::: {.grid}

::: {.g-col-3}
**Take-Home Exam**
:::

::: {.g-col-9}

There is one take-home exam on **Tuesday, June 2**.
The exam will assess students’ ability to use material from the first-half of the semester to answer open-ended questions about a real dataset.
Students will have from **9am to 11:59pm on Tuesday, June 2** to complete the exam.
The exam is designed to take 2--3 hours, but the 15-hour time window is only meant to provide some flexibility and alleviate time pressure.
More details will be given closer to the exam date.

:::

:::

::: {.grid}

::: {.g-col-3}
**Final Project**
:::

::: {.g-col-9}
The purpose of this project is to assess students’ ability to create high-quality data visualizations and communicate their work in common formats: reports and presentations.
These communication skills are important in statistics and data science.
The deliverables can be part of your portfolio, as you apply for jobs, graduate schools, and other opportunities.

Students will work individually to analyze a dataset of their choosing.
The project will culminate in a report and a short video recording.
More details about the project will be provided later.

:::

:::

## Logistics and Policies

::: {.grid}

::: {.g-col-3}
**Regrades**
:::

::: {.g-col-9}

Any regrade requests for lab and homework assignments must be **submitted on Gradescope within 48 hours** of grade release.
Do not make a request via email.
If a regrade request is made more than 48 hours after grade release, it will not be processed.
:::

:::

::: {.grid}

::: {.g-col-3}
**Extensions**
:::

::: {.g-col-9}

In general, late assignments will not be accepted.
However, extensions may be granted for illness, family emergencies, job interviews, or religious reasons.
To receive an extension, you must contact the instructor at least **36 hours** before the due date.
It is up to the instructor to decide if an extension may be granted.
Note that if your request does not involve an illness, family emergency, job interview, or religious reason, then it is extremely unlikely that an extension will be granted.
:::

:::

::: {.grid}

::: {.g-col-3}
**Disability Services** 
:::

::: {.g-col-9}
If you require a special accommodation, please visit the [Office of Disability Resources](https://www.cmu.edu/disability-resources/).
No accommodations can be provided without proper documentation.
:::

:::

::: {.grid}

::: {.g-col-3}
**Integrity** 
:::

::: {.g-col-9}
Cheating, plagiarism, and/or unauthorized assistance on assignments will be dealt with in accordance with the [CMU Policy on Academic Integrity](https://www.cmu.edu/policies/student-and-student-life/academic-integrity.html). 
:::

:::

::: {.grid}

::: {.g-col-3}
**Collaboration**
:::

::: {.g-col-9}
You are encouraged to discuss assignments with your classmates.
But **all the work you turn in must be your own**.
You must independently write your own code, generate your own graphics, and write your own solutions and reports.
Copied or nearly identical submissions will be considered cheating and plagiarism.
:::

:::

::: {.grid}

::: {.g-col-3}
**External Sources**
:::

::: {.g-col-9}
External sources (e.g., books, websites, etc.) should only be used to support your work, not to obtain your work.
You may use external sources to look up code documentation, find useful packages, find explanations for error messages, or clarify lecture materials.
You may not use them to copy code, text, or graphics without proper attribution.
Do not copy old solutions, and do not consult or read them.
:::

:::
::: {.grid}

::: {.g-col-3}
**Generative AI** 
:::

::: {.g-col-9}
When allowed, you may consult generative AI tools.
However, you must take intellectual responsibility for your code, analysis, and writing, and be able to explain and defend every decision.
You must do the thinking, not generative AI.
You may not use generative AI to come up with analysis or interpretation for you, only to augment your own work.
If you use a generative AI tool, you must disclose and explain what you use it for.
:::

:::

## Calendar

*(subject to change)*

| Date                    | Session            | Assignment     |
|-------------------------|--------------------|----------------|
| **Week 1**              |                    |                |
| May 11 (Monday)         | Lecture 1          |                |
| May 12 (Tuesday)        | Lab 1              | Lab 1 due      |
| May 13 (Wednesday)      | Lecture 2          |                |
| May 14 (Thursday)       | Lab 2              | Lab 2 due      |
| May 15 (Friday)         | Lecture 3          | Homework 1 due |
| **Week 2**              |                    |                |
| May 18 (Monday)         | Lecture 4          |                |
| May 19 (Tuesday)        | Lab 3              | Lab 3 due      |
| May 20 (Wednesday)      | Lecture 5          |                |
| May 21 (Thursday)       | Lab 4              | Lab 4 due      |
| May 22 (Friday)         | Lecture 6          | Homework 2 due |
| **Week 3**              |                    |                |
| May 25 (Monday)         | Memorial Day       |                |
| May 26 (Tuesday)        | Lab 5              | Lab 5 due      |
| May 27 (Wednesday)      | Lecture 7          | Critique 1 due |
| May 28 (Thursday)       | Lab 6              | Lab 6 due      |
| May 29 (Friday)         | Lecture 8          | Homework 3 due |
| **Week 4**              |                    |                |
| June 1 (Monday)         | Lecture 9          |                |
| June 2 (Tuesday)        | NO LAB             | Take-home due  |
| June 3 (Wednesday)      | Lecture 10         |                |
| June 4 (Thursday)       | Lab 7              | Lab 7 due      |
| June 5 (Friday)         | Lecture 11         | Homework 4 due |
| **Week 5**              |                    |                |
| June 8 (Monday)         | Lecture 12         |                |
| June 9 (Tuesday)        | Lab 8              | Lab 8 due      |
| June 10 (Wednesday)     | Lecture 13         | Critique 2 due |
| June 11 (Thursday)      | Lab 9              | Lab 9 due      |
| June 12 (Friday)        | Lecture 14         | Homework 5 due |
| **Week 6**              |                    |                |
| June 15 (Monday)        | Lecture 15         |                |
| June 16 (Tuesday)       | TBD                |                |
| June 17 (Wednesday)     | TBD                | Project due    |
